import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Arnifi | Company Applications | Details",
  description: "Generated by create next app",
};

const ApplicationDetailsLayout = ({
  children,
}: {
  children: React.ReactNode;
}) => {
  return children;
};

export default ApplicationDetailsLayout;
